config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users
  devise_for :users,  :controllers => { :registrations => 'users/registrations', :sessions => 'users/sessions', :invitations => 'users/invitations'}
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root 'items#index'
  resources :users, only: [:index, :update, :create]
  resources :items, only: [:index, :new, :create, :show] do
    resources :reviews, only: [:new, :create]
    resources :orders, only: [:index, :create, :show]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  attr_reader :image

  mount_uploader :image, ImageUploader
  has_many :orders
  has_many :reviews
  belongs_to :user, optional: true
  has_many :likes, dependent: :destroy

    def like_user(user_id)
      likes.find_by(user_id: user_id)
    end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :item, counter_cache: :likes_count
  belongs_to :user
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :item
  belongs_to :user
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :item
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :invitable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :invite_for => 24.hours

  has_many :items
  has_many :orders
  has_many :likes
  has_many :reviews

  validates :encrypted_password, presence: true, uniqueness: true,
             length: {minimum: 8}
  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
  validates :admin_flg, null: false, default: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
    def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
     devise_parameter_sanitizer.permit(:sign_up, keys: [:admin_flg])
     devise_parameter_sanitizer.permit(:invite, keys: [:email])
     devise_parameter_sanitizer.permit(:accept_invitation, keys: [:name])
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # before_action :set_item, only: [:show]
  before_action :authenticate_user!

  def index
    @earning_ranking = Order.group(:item_image,:item_id).order('count_item_image Desc').limit(5).count(:item_image).keys
    # @orders = Order.find(params[:item_id])
    @user = User.find(current_user[:id])
    @item_all = Item.order("created_at Desc").limit(6)
    @item_recommend = Item.where(recommend: 1).order("RAND()").limit(6)
    @item_ranking = Item.where(popular: 1).order("created_at Desc").limit(6)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    # binding.pry
    @item = Item.find(params[:id])
    @review = @item.reviews.order("created_at Desc")
    @likes = Like.where(item_id: params[:item_id])
  end

  private

  def item_params
    params.require(:item).permit(:image, :name, :price, :description, :count, :number, :recommend, :popular)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    # binding.pry
    @like = Like.create(user_id: current_user.id, item_id: params[:item_id])
    @likes = Like.where(item_id: params[:item_id])
    @item = Item.find(params[:id])
    # binding.pry
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, item_id: params[:item_id])
    like.destroy
    @likes = Like.where(item_id: params[:item_id])
    @item = Item.find(params[:id])
  end

  private

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    # binding.pry
    @orders = current_user.orders(params[:id])
    @item = current_user.orders(params[:item_id])
  end

  def create
    @order = Order.new(order_params)
    if @order.save
      @item = Item.find(params[:item_id])
      @item.count -= 1
      @item.save
      NoticeMailer.sendmail_confirm(current_user).deliver_now
      redirect_to root_path, notice: "商品を購入しました。完了の場合はメールが届きますのでご確認をお願いいたします。"
    else
      redirect_to item_path, alert: "購入に失敗しました"
    end
  end

  def show
  end

  private

  def order_params
    params.permit(:item_id).merge(user_id: current_user.id, item_name: params[:name], item_price: params[:price], item_image: params[:image])
  end

  def count_params
    params.permit(:count)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    # binding.pry
    @item = Item.find(params[:item_id])
    @review = Review.new
  end

  def create
    # binding.pry
    @item = Item.find(params[:item_id])
    @review = Review.new(review_params)
    # binding.pry
    if @review.save
      redirect_to root_path, notice: 'レビュー入力ありがとうございました。'
    else
      render :new
    end
  end

private

  def review_params
    # binding.pry
    params.require(:review).permit(:review).merge(user_id: current_user.id, star_rate: params[:star_rate], item_id: params[:item_id])
  end

end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    # @user = User.find(current_user[:id])
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path, notice: "ユーザー情報を更新しました"
    else
      render :edit
    end
  end

  def create
  end

  private

  def user_params
    # binding.pry
    params.require(:user).permit(:name,:email)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_content.html.haml
.content
  .bg-slider
    %h1.bg-slider__title
      SUMMER SALE NOW
  .new_item
    .new_item__title
      新作商品
    .new_item__image
      - item_all.each do |item|
        .new_item__image_image
          = image_tag item.image
          %p.new_item__image_name
            = link_to item.name, item_path(item.id,user.id)
          %p.new_item__image_price
            #{ item.price } 円 ( 税込 20%off! )<br>

  .recommended
    .recommended__title
      おすすめ商品
    .recommended__images
      - item_recommend.each do |item|
        .recommended__images_image
          = image_tag item.image
          %p.recommended__images_name
            = link_to item.name, item_path(item.id,user.id)
          %p.recommended__images_price
            #{ item.price } 円 ( 税込 15%off! )

  .ranking
    .ranking__title
      夏の人気アイテム
    .ranking__image
      - item_ranking.each do |item|
        .ranking__image_image
          = image_tag item.image
          %p.ranking__image_name
            = link_to item.name, item_path(item.id,user.id)
          %p.ranking__image_price
            #{ item.price } 円 (税込 18%off! )

app/views/items/_leftbar.html.haml
.leftbar
  .title
    探す
  %ul
    %li
      ブランドから探す
    %li
      ショップから探す
    %li
      ランキングから探す
    %li
      こだわり条件から探す

  .title
    カテゴリー
  %ul
    %li
      トップス
    %li
      ジャケット
    %li
      パンツ
    %li
      オールインワン
    %li
      スカート
    %li
      ワンピース
    %li
      スーツ/ネクタイ
    %li
      バッグ
    %li
      シューズ
    %li
      ファッション
    %li
      財布/小物
    %li
      時計
    %li
      ヘアアクセサリー
    %li
      アクセサリー
    %li
      アンダーウェア
    %li
      レッグウェア
    %li
      帽子
    %li
      インテリア
    %li
      食器/キッチン
    %li
      雑貨/ホビー/スポーツ
    %li
      コスメ/香水
    %li
      音楽/本・雑貨
    %li
      水着/着物・浴衣
    %li
      マタニティー/ベビー
    %li
      その他

  .title
    お気に入り
  %ul
    %li
      アイテム
    %li
      ブランド
    %li
      ショップ

app/views/items/_rightbar.html.haml
.rightbar
  .title
    購入ランキング
  .ranking
    - earning_ranking.each.with_index(1) do |ranking, i|
      .ranking_rank
        第#{i}位
      .ranking_image
        -# -binding.pry
        = link_to image_tag(ranking[0]),item_path(ranking[1])

  .title
    ニュース
  %ul
    %li
      おすすめ1
    %li
      おすすめ2
    %li
      おすすめ3
    %li
      おすすめ4
    %li
      おすすめ5

app/views/items/_topbar.html.haml
%body.drawer.drawer--top.drawer--navbarTopGutter
%header.drawer-navbar.drawer-navbar--fixed{:role => "banner"}
  .drawer-container
    .drawer-navbar-header
      %a.drawer-brand{:href => "/items"} ZOZOTOWN
      %button.drawer-toggle.drawer-hamburger{:type => "button"}
        %span.sr-only toggle navigation
        %span.drawer-hamburger-icon
    %nav.drawer-nav{:role => "navigation"}
      %ul.drawer-menu
        %li.drawer-dropdown
          %a.drawer-menu-item{"aria-expanded" => "false", "data-target" => "#", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            #{current_user.name} 様
            %span.drawer-caret
          %ul.drawer-dropdown-menu
            %li
              %a.drawer-dropdown-menu-item{:href => "/users"} マイページ
            %li
              %a.drawer-dropdown-menu-item{:href => "/items/:item_id/orders"} 購入履歴
            %li
              %a.drawer-dropdown-menu-item{:href => "/users/invitation/new"} 友人を招待する
            %li
              %a.drawer-dropdown-menu-item{:href => "/users/sign_out"} ログアウト
        %li.drawer-dropdown
          %a.drawer-menu-item{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            設定
            %span.drawer-caret
          -if @user && @user.admin_flg == true #管理人専用ページ
            %ul.drawer-dropdown-menu
              %li
                %a.drawer-dropdown-menu-item{:href => "/users"} ユーザー情報
              %li
                %a.drawer-dropdown-menu-item{:href => "/items/new"} 管理人ページ
          -else #一般ユーザーページ
            %ul.drawer-dropdown-menu
              %li
                %a.drawer-dropdown-menu-item{:href => "/users"} ユーザー情報
              %li
                %a.drawer-dropdown-menu-item{:href => ""} よくある質問
              %li
                %a.drawer-dropdown-menu-item{:href => ""} 初めての方へ
.subbar
  %p.all
    すべて
  %p.men
    メンズ
  %p.women
    レディース
  %p.kids
    キッズ

app/views/items/edit.html.haml
.register-page
  .title
    .title__content
      %i.fa.fa-id-card
      %p.explain
        商品登録画面
  .date
    .data__info
      .field
        = form_for(@item) do |f|
          .field-label
            =f.label :image do
              %p 画像を選択
              = f.file_field :image, class: "field-label__image"
          .field-label
            = f.label :name, value: "商品名"
            = f.text_field :name
          .field-label
            = f.label :price, value: "値段"
            = f.text_field :price
          .field-label
            = f.label :description, value: "商品説明"
            = f.text_field :description
          .field-label
            = f.label :count, value: "在庫数"
            = f.text_field :count
          .field-label
            = f.label :number, value: "品番"
            = f.text_field :number
          .field-label
            = f.label :recommend, value: "おすすめ商品"
            = f.text_field :recommend
          .field-label
            = f.label :popular, value: "夏の人気商品"
            = f.text_field :popular
          .field-label
            以上の内容を登録→
            = button_tag type: 'submit', name: 'news', class: "field-label__btn" do
              %i.fa.fa-paper-plane

app/views/items/index.html.haml
= render "topbar"
= render "leftbar"
= render "content", item_recommend: @item_recommend, item_ranking: @item_ranking, item_all: @item_all, user: @user, review: @review
= render "rightbar", earning_ranking: @earning_ranking, user: @user, orders: @orders

%p#page-top
  %a{:href => "#wrap"} PAGE TOP
%p.graph
  -# = bar_chart @chart_data, height: "600px", width: "300px"

app/views/items/new.html.haml
.register-page
  .title
    .title__content
      %i.fa.fa-id-card
      %p.explain
        商品登録画面
  .date
    .data__info
      .field
        = form_for(@item) do |f|
          .field-label
            =f.label :image do
              %p 画像を選択
              = f.file_field :image, class: "field-label__image"
          .field-label
            = f.label :name, value: "商品名"
            = f.text_field :name
          .field-label
            = f.label :price, value: "値段"
            = f.text_field :price
          .field-label
            = f.label :description, value: "商品説明"
            = f.text_field :description
          .field-label
            = f.label :count, value: "在庫数"
            = f.text_field :count
          .field-label
            = f.label :number, value: "品番"
            = f.text_field :number
          .field-label
            = f.label :recommend, value: "おすすめ商品"
            = f.text_field :recommend
          .field-label
            = f.label :popular, value: "夏の人気商品"
            = f.text_field :popular
          .field-label
            以上の内容を登録→
            = button_tag type: 'submit', class: "field-label__btn" do
              %i.fa.fa-paper-plane

app/views/items/show.html.haml
= render 'topbar'

.shopping
  - if @item.count >= 1
    .cart
      .cart__title
        ご注文ありがとうございます。<br>
        チェックしたアイテム
      .cart__info
        .cart__info_image
          = image_tag @item.image
        .cart__info_detail
          .cart__info_detail_name
            商品名 #{ @item.name }
          .cart__info_detail_count
            在庫数: #{ @item.count }
          .cart__info_detail_description
            商品概要: #{ @item.description }
          .cart__info_detail_price
            小計　¥ #{ @item.price }
          = render 'likes/like', locals: {item: @item}

    .bill
      .bill__pay
        商品金額 ¥ #{ @item.price }
      .bill__postage
        送料　　¥250
      .bill__commission
        手数料　¥250
      .bill__sum
        合計金額 ¥ #{ @item.price + 500 }

    .check
      .check__complete
        = link_to  "この商品を購入する", item_orders_path(@item, name: @item.name, price: @item.price, image: @item.image ), method: :POST, class: "btn_submit"
      .check__return
        = link_to "購入をキャンセルする", root_path
      .check__comment
        = link_to "この商品のレビューを書く", new_item_review_path(@item.id)
    - @review.each do |review|
      .review
        .review__star_rate
          - if review.star_rate == 5
            ★★★★★
          - elsif review.star_rate == 4
            ★★★★
          - elsif review.star_rate == 3
            ★★★
          - elsif review.star_rate == 2
            ★★
          - else review.star_rate ==1
            ★
        .review__date
          #{review.created_at}
        .review__review
          #{review.review}
        .review__icon
          このレビューは参考になりましたか？

  - else @item.count = 0
    .sold-out
      .sold-out__title
        ご注文いただきました商品は現在品切れとなっております。<br>
        入荷までお待ちください。
      .sold-out__info
        .sold-out__info_image
          = image_tag("sold_out2.jpg")
        .sold-out__info_detail
          .sold-out__info_detail_name
            商品名: #{ @item.name }
          .sold-out__info_detail_count
            在庫数: #{ @item.count }
          .sold-out__info_detail_description
            商品概要: #{ @item.description }
          .sold-out__info_detail_price
            小計　¥ #{ @item.price }
          .sold-out__info_detail_link
            = link_to "前画面に戻る", root_path, class: "btn_return"

app/views/likes/_like.html.haml
- if user_signed_in?
  - if @item.like_user(current_user.id)
    = button_to item_like_path(@likes, item_id: @item.id), method: :delete, id: "like_button", remote: true do
      = image_tag("icon_red_heart.svg")
      %span
        = @item.likes_count
  - else
    = button_to item_likes_path(@item), id: "like-button", remote: true do
      = image_tag("icon_heart.svg")
      %span
        = @item.likes_count
- else
  = image_tag("icon_heart.svg")
  %span
    = @item.likes_count

app/views/likes/create.js.haml
$("#like-bottons").html("<%= j(render partial: 'like', locals: { items: @items, likes: @likes, like: @like }) %>")

app/views/likes/destroy.js.haml
$("#like-bottons").html("<%= j(render partial: 'like', locals: { items: @items, likes: @likes}) %>");

app/views/orders/index.html.haml
= render 'items/topbar'
.user_info
  #{current_user.name} 様
.purchase_history
  購入履歴
  .purchase_history__item
    - @orders.each do |orders|
      %ul
        %li
          %p.purchase_history__item_image
            = image_tag orders.item_image
          .purchase_history__item_detail
            %p.purchase_history__user_detail__name
              お名前 : #{current_user.name} 様
            %p.purchase_history__item_detail__name
              商品名 : #{orders.item_name}
            %p.purchase_history__item_detail__price
              金額 : ¥#{orders.item_price}
            %p.purchase_history__item_detail__purchase_date
              購入日 : #{orders.created_at}
            = link_to "この商品についてレビューを書く", new_item_review_path(orders.item.id)

app/views/orders/show.html.haml
= render 'items/topbar'